version: '3.4'

services:
  opuspac.api:
    image: ${DOCKER_REGISTRY-}opuspacapi
    build:
      context: .
      dockerfile: Opuspac.Api/Dockerfile
    networks:
      - main

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: opuspac
    ports:
      - 5432:5432
    networks:
      - main

volumes:
   postgres-data:
  
networks:
  main: