export const administrationInstructions = [
  "Intravenosa",
  "Oral",
  "Intramuscular",
  "Subcutânea",
  "Tópica",
  "Respiratória",
  "Oftálmica",
  "Otológica",
  "Nasal",
  "Retal",
  "Sublingual",
  "Intradérmica",
  "Intratecal",
  "Intra-articular",
];
